---

########
# Install packages

- name: Install packages
  apt:
    name:
      - keepalived
    state: present

########
# Configure firewall rules

- name: Enable firewall rules for VRRP
  ufw:
    protocol: any
    direction: in
    to_ip: 224.0.0.0/8
    rule: allow

########
# Keepalived configuration

- name: Keepalived configuration
  template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.j2
    mode: 0644
    owner: root
    group: root
  register: keepalived_config

########
# Configure notify script

- name: Add notify script
  template:
    dest: "{{ notify_script_location }}"
    src: notify.j2
    mode: 0755
    owner: root
    group: root
  register: notify_script

########
# Configure service and restart if necessary

- name: Keepalived Service
  service: 
    name: keepalived
    enabled: true
    state: "{{ 'restarted' if keepalived_config.changed or notify_script.changed else 'started' }}"

